### ISSUE TITLE
Possible osgameclones.com addition

### ISSUE THREAD

**Issue by wonea** [teruk/movbizz#4]
This game sounds absolutely fabulous. I would like to add it osgameclones.com but I'm struggling with references. Neither MobyGames or Wikipedia lists this game. How did you hear about it?

**Comment by teruk** [comment]
I had the original for my C64 and I played it a lot. You find references for the mostly on c64-sites like Gamebase64 (http://www.gamebase64.com/game.php?id=14674&d=18) or CSDB (http://csdb.dk/release/?id=126115).

It would be awesome, if you could add to osgameclones.

**Comment by wonea** [comment]
Thanks, I'll take GameBase64 as the reference. As you can see I've created a pull request into osgamesclones.com, hopefully this will be merged soon and appear on the website.

**Comment by teruk** [comment]
thank you, I appreciate it
